# Generated by Django 5.2.14 on 2026-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlassClinicalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("clinical_qa", "Clinical Q&A"),
                            ("differential", "Differential Diagnosis"),
                            ("treatment_plan", "Treatment Plan"),
                            ("summarization", "Patient Summarization"),
                            ("documentation", "Documentation"),
                            ("triage", "Triage"),
                        ],
                        default="clinical_qa",
                        max_length=50,
                    ),
                ),
                ("question", models.TextField()),
                ("patient_context", models.TextField(blank=True, default="")),
                ("prompt_sent", models.TextField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("extracted_content", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(default="completed", max_length=30)),
                ("error_message", models.TextField(blank=True, default="")),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
