# Generated by Django 5.2.14 on 2026-05-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glassclinicalrequest",
            name="citations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="glassclinicalrequest",
            name="detected_schema",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="glassclinicalrequest",
            name="usage",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="glassclinicalrequest",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("clinical_qa", "Clinical Q&A"),
                    ("differential", "Differential Diagnosis"),
                    ("treatment_plan", "Treatment Plan"),
                    ("summarization", "Patient Summarization"),
                    ("documentation", "Documentation"),
                    ("triage", "Triage"),
                    ("raw_prompt", "Raw Prompt"),
                ],
                default="clinical_qa",
                max_length=50,
            ),
        ),
    ]
