# Generated by Django 5.2.14 on 2026-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_glassclinicalrequest_citations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalAIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("clinical_qa", "Clinical Q&A"),
                            ("draft_ddx", "Draft DDx"),
                            ("draft_assessment_plan", "Draft Assessment & Plan"),
                            ("draft_hpi", "Draft HPI"),
                            ("draft_clinic_note", "Draft Clinic Note"),
                            ("draft_patient_handout", "Draft Patient Handout"),
                            ("raw_prompt", "Raw Prompt"),
                        ],
                        default="clinical_qa",
                        max_length=50,
                    ),
                ),
                ("question", models.TextField()),
                ("patient_context", models.TextField(blank=True, default="")),
                ("prompt_sent", models.TextField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("extracted_content", models.TextField(blank=True, default="")),
                ("structured_output", models.JSONField(blank=True, default=dict)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("references", models.JSONField(blank=True, default=list)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("detected_schema", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GlassClinicalRequest",
        ),
    ]
